p2p_port = 0

[[nodes]]
json_rpc_port = 4201
eth_chain_id = 0x8001
consensus.consensus_timeout = { secs = 5, nanos = 0 }
consensus.genesis_deposits = [
    ["b27aebb3b54effd7af87c4a064a711554ee0f3f5abf56ca910b46422f2b21603bc383d42eb3b927c4c3b0b8381ca30a3", "12D3KooWESMZ2ttSxDwjfnNe23sHCqsJf6sNEKwgHkdgtCHDsbWU", "10000000000000000000000000", "7E5F4552091A69125d5DfCb7b8C2659029395Bdf"],
]
consensus.genesis_accounts = [
    # Accounts with private key 0x2, 0x3, 0x4.
    # Don't use account with priv key = 0x1 since it's also used for voting rewards
    ["2B5AD5c4795c026514f8317c7a215E218DcCD6cF", "5000000000000000000000"],
    ["6813Eb9362372EEF6200f3b1dbC3f819671cBA69", "5000000000000000000000"],
    ["1efF47bc3a10a45D4B230B5d10E37751FE6AA718", "5000000000000000000000"],
    ["8D393a22E4476fF8212DE13fE1939De2a236F0A7", "5000000000000000000000"],
    ["9cB422D2Fabe9622ed706ad5D9d3fFd2cDd1C001", "5000000000000000000000"],
    ["AcE5F1e883d3e02A1b2C78F6909a8C0430C6Fb12", "5000000000000000000000"],
]

# Reward parameters
consensus.rewards_per_hour = "51_000_000_000_000_000_000_000"
consensus.blocks_per_hour = 3600
consensus.minimum_stake = "10_000_000_000_000_000_000_000_000"
# Gas parameters
consensus.eth_block_gas_limit = 84000000
consensus.gas_price = "4_761_904_800_000"
consensus.local_address = "host.docker.internal"
consensus.scilla_lib_dirs = ["/scilla/0/_build/default/src/stdlib/", "/scilla-libs"]
