otlp_collector_endpoint = "http://otel-collector:4317"

[[nodes]]
# These (public key, peerId, stake, rewardAddress) tuples correspond to the private keys of all four nodes in `docker-compose.yaml`.
consensus.genesis_deposits = [
    ["b27aebb3b54effd7af87c4a064a711554ee0f3f5abf56ca910b46422f2b21603bc383d42eb3b927c4c3b0b8381ca30a3", "12D3KooWESMZ2ttSxDwjfnNe23sHCqsJf6sNEKwgHkdgtCHDsbWU", "10000000000000000000000000", "7E5F4552091A69125d5DfCb7b8C2659029395Bdf"],
    ["b37fd66aef29ca78a82d519a284789d59c2bb3880698b461c6c732d094534707d50e345128db372a1e0a4c5d5c42f49c", "12D3KooWJc2nBgNiSi14GcYaGmU8FoQsRkmhfMnaB1mHmPiBPZHd", "10000000000000000000000000", "2B5AD5c4795c026514f8317c7a215E218DcCD6cF"],
    ["ab035d6cd3321c3b57d14ea09a4f3860899542d2187b5ec87649b1f40980418a096717a671cf62b73880afac252fc5dc", "12D3KooWLA4xVjiGszqmYJmt8E1NTurVeCujDi17FoSzSDDDKUjT", "10000000000000000000000000", "6813Eb9362372EEF6200f3b1dbC3f819671cBA69"],
    ["985e3a4d367cbfc966d48710806612cc00f6bfd06aa759340cfe13c3990d26a7ddde63f64468cdba5b2ff132a4639a7f", "12D3KooWPXw2dXBRH1bT4vcNos9f6W2KoFTiarqptBuTzxaXg7zu", "10000000000000000000000000", "1efF47bc3a10a45D4B230B5d10E37751FE6AA718"],
]
consensus.genesis_accounts = [
    # Accounts with private key 0x2, 0x3, 0x4.
    # Don't use account with priv key = 0x1 since it's also used for voting rewards
    ["2B5AD5c4795c026514f8317c7a215E218DcCD6cF", "50000000000000000000000000"],
    ["6813Eb9362372EEF6200f3b1dbC3f819671cBA69", "50000000000000000000000000"],
    ["1efF47bc3a10a45D4B230B5d10E37751FE6AA718", "50000000000000000000000000"],
    ["29e562f73488c8a2bB9Dbc5700b361D54b9B0554", "50000000000000000000000000"],
    ["8D393a22E4476fF8212DE13fE1939De2a236F0A7", "50000000000000000000000000"],
    ["9cB422D2Fabe9622ed706ad5D9d3fFd2cDd1C001", "50000000000000000000000000"],
    ["AcE5F1e883d3e02A1b2C78F6909a8C0430C6Fb12", "50000000000000000000000000"],
    ["1958b2f7b5c476F5e8FeBdEFeba5EC39E2f20288", "50000000000000000000000000"],

    # CREATE2 deployer (see https://github.com/Arachnid/deterministic-deployment-proxy)
    ["3fAB184622Dc19b6109349B94811493BF2a45362", "50000000000000000000000000"],

    # Anvil
    ["f39Fd6e51aad88F6F4ce6aB8827279cffFb92266", "50000000000000000000000000"],
    ["70997970C51812dc3A010C7d01b50e0d17dc79C8", "50000000000000000000000000"],
    ["3C44CdDdB6a900fa2b585dd299e03d12FA4293BC", "50000000000000000000000000"],
    ["90F79bf6EB2c4f870365E785982E1f101E93b906", "50000000000000000000000000"],
    ["15d34AAf54267DB7D7c367839AAf71A00a2C6A65", "50000000000000000000000000"],
    ["9965507D1a55bcC2695C58ba16FB37d819B0A4dc", "50000000000000000000000000"],
    ["976EA74026E726554dB657fA54763abd0C3a0aa9", "50000000000000000000000000"],
    ["14dC79964da2C08b23698B3D3cc7Ca32193d9955", "50000000000000000000000000"],
    ["23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f", "50000000000000000000000000"],
    ["a0Ee7A142d267C1f36714E4a8F75612F20a79720", "50000000000000000000000000"],
]

# Reward parameters
consensus.rewards_per_hour = "51_000_000_000_000_000_000_000"
consensus.blocks_per_hour = 3600
consensus.minimum_stake = "10_000_000_000_000_000_000_000_000"
# Gas parameters
consensus.eth_block_gas_limit = 84000000
consensus.gas_price = "4_761_904_800_000"